### ISSUE TITLE
Sort by name doesn't always sort by name

### ISSUE THREAD

**Issue by kotenok2000** [pointfeev/CreamInstaller#227] opened 2024-06-20 21:23 UTC
###### Describe the bug and/or provide an image of the exception dialog box:
![image](https://github.com/pointfeev/CreamInstaller/assets/8822292/6622d983-8531-4928-915d-77030fffe8c4)

**Comment by ZotoBro** [comment] 2024-06-21 10:36
It sorts by name then platform, so I think this is just intended behaviour and not a bug.

**Comment by pointfeev** [comment] 2024-07-22 07:14
Strings were being sorted using ordinal comparison. This will be fixed in the next version by using culture-specific comparison.

**Closed by pointfeev** 2024-07-22 07:14 UTC
Labels: Bug, Work in Progress
